django-project/authentication/urls.py
from django.urls import path
from django.urls import include

from .views import UserProfileCreateView
from .views import UserProfileDetailView

urlpatterns = [
    path('all-profile/', UserProfileCreateView.as_view(), name='all-profile'),
    path('profile/<int:pk>', UserProfileDetailView.as_view(), name='profile')
]

django-project/config/urls.py
# import main.views as main

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # main urls
    path('', include('main.urls')),

    # admin urls
    path('admin/', admin.site.urls),

    # API urls
    path('', include('api.urls')),
    path('api/authentication/', include('authentication.urls')),

    # AUTH endpoints
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

django-project/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.main, name='home'),
    path('food', views.food, name='food'),
    path('exercise', views.exercise, name='exercise'),
    path('reports', views.reports, name='reports'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact')
]

django-project/authentication/models.py
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
    )

    description = models.TextField(blank=True, null=True)

    create_at = models.DateTimeField(auto_now_add=True)

    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.email}'

django-project/main/models.py
from datetime import date, datetime

from django.db import models
from django_countries.fields import CountryField


class User(models.Model):
    class Meta:
        verbose_name = u'User'

    GOAL = (
        ('lose', 'Lose Weight'),
        ('maintain', 'Maintain Weight'),
        ('gain', 'Gain Weight')
    )
    ACTIVITY_LEVEL = (
        ('not_active', 'Not Very Active'),
        ('lightly_active', 'Lightly Active'),
        ('active', 'Active'),
        ('very_active', 'Very Active')
    )
    SEX = (
        ('male', 'Male'),
        ('female', 'Female')
    )

    WEAK_GOAL = (
        ('one-quarter', 'Lose 0.25 kilograms per week'),
        ('one-half', 'Lose 0.5 kilograms per week (Recommended)'),
        ('three-fourths', 'Lose 0.75 kilograms per week'),
        ('kilo', 'Lose 1 kilograms per week')
    )
    # goal = models.CharField(
    #     max_length=20,
    #     choices=GOAL,
    #     default='maintain',
    #     verbose_name=u'Goal'
    # )
    # activity_level = models.CharField(
    #     max_length=20,
    #     choices=ACTIVITY_LEVEL,
    #     default='active',
    #     verbose_name=u'Level'
    # )
    # sex = models.CharField(
    #     max_length=10,
    #     choices=SEX,
    #     default='email',
    #     verbose_name=u'Sex'
    # )
    # birthday = models.DateTimeField(
    #     max_length=40,
    #     default=datetime.now,
    #     verbose_name=u'Birthday'
    # )
    # country = CountryField(
    #     default='Poland',
    #     verbose_name=u'Country'
    # )
    height = models.FloatField(
        default=170,
        verbose_name=u'Height'
    )
    current_weight = models.FloatField(
        default=70,
        verbose_name=u'Current Weight'
    )
    goal_weight = models.FloatField(
        default=57,
        verbose_name=u'Goal Weight'
    )
    # week_goal = models.CharField(
    #     max_length=30,
    #     choices=WEAK_GOAL,
    #     default='three-fourths',
    #     verbose_name=u'Week Goal'
    # )
    email = models.EmailField(
        max_length=254,
        verbose_name=u'Email',
        default='user@gmail.com'
    )
    username = models.CharField(
        default='anonymous',
        max_length=100,
        verbose_name=u'Username',
        unique=True
    )

    def __repr__(self):
        return f'<User {self.username}>'


class Post(models.Model):
    user = models.ForeignKey(
        User,
        related_name="posts",
        on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __repr__(self):
        return f'<User {self.user} {self.body}>'

django-project/main/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "rows": 3,
                "placeholder": "What's on your mind?",
                "class": "textarea is-success is-medium form-control form-control form-status border-0 py-1 px-0",
            }
        ),
        label="",
    )

    class Meta:
        model = Post
        exclude = ("username", )

django-project/authentication/views.py
from django.shortcuts import render
from rest_framework.generics import ListCreateAPIView
from rest_framework.generics import RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticated

from .models import UserProfile
from .serializers import UserProfileSerializer
from .permissions import IsOwnerProfileOrReadOnly


class UserProfileCreateView(ListCreateAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        user = self.request.user
        serializer.save(user=user)


class UserProfileDetailView(RetrieveUpdateDestroyAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer
    permission_classes = [IsAuthenticated, IsOwnerProfileOrReadOnly]

django-project/main/views.py
from datetime import datetime

from django.http import HttpResponse

from .models import User
from .models import Post
from django.shortcuts import render, redirect
from django.template import loader
from .utils import get_user
from .utils import paginate
from .forms import PostForm


def main(request):
    user_profile = User.objects.first()
    comments = Post.objects.all()
    form = PostForm(request.POST or None)
    if request.method == "POST":
        form = PostForm(request.POST or None)
        print(form.is_valid())
        if form.is_valid():
            print("it's valid!!")
            post = form.save(commit=False)
            post.username = request.user
            post.save()
            return redirect("main:home")
    context = {
        'user_profile': user_profile,
        'comments': comments,
        "form": form,
        'navbar': 'home',
        'tabs': ['Home', 'Goals', 'Check-In', 'Mail', 'Profile', 'Friends', 'Settings']
    }

    return render(request, "home.html", context)


def food(request):
    return render(
        request,
        "food.html",
        {
            'navbar': 'food',
            'tabs': ['Food Diary', 'Database', 'My Foods', 'My Meals', 'Recipes', 'Settings']
         }
    )


def exercise(request):
    return render(
        request,
        "exercise.html",
        {
            'navbar': 'exercise',
            'tabs': ['Exercise Diary', 'Database', 'My Exercises', 'Settings']
        }
    )


def reports(request):
    return render(
        request,
        "reports.html",
        {
            'navbar': 'reports',
            'tabs': ['home', 'goals', 'check-in', 'mail']
        }
    )


def about(request):
    return render(
        request,
        "about.html",
        {
            'title': "About",
            'content': "About Page"
        }
    )


def contact(request):
    return render(
        request,
        "contact.html",
        {
            'title': "Contact",
            'content': "Contact Page"
        }
    )

django-project/templates/about.html
<html>
    <head>
        <title>{{ title }}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'site.css' %}" />
    </head>
    <body>
        <div><a href="/">Home</a></div>
        {{ content }}
    </body>
</html>

django-project/templates/contact.html
<html>
    <head>
        <title>{{ title }}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'site.css' %}" />
    </head>
    <body>
        <div><a href="/">Home</a></div>
        {{ content }}
    </body>
</html>

django-project/templates/exercise.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django-project/templates/food.html
{% extends 'index.html' %}

{% block tabs %}
    {% if tabs %}
        {% for tab in tabs %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">{{ tab }}</a>
            </li>
        {% endfor %}
    {% endif %}
{% endblock tabs %}

{% block content %}
    <div class="wrap m-auto mt-4 position-relative text-start d-inline-block overflow-hidden">
        <div class="content float-start d-inline position-relative w-100">
            <div class="main float-start">
                <div class="diary d-flex border-bottom border-secondary border-3">
                    <h1>Your Food Diary For:</h1>
                    <div class="date-controls m-auto ms-3">
                        <div class="">
                            <input class="form-control" type="date" />
                            <span></span>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock content %}

django-project/templates/home.html
{% extends 'index.html' %}

{% block tabs %}
    {% if tabs %}
        {% for tab in tabs %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">{{ tab }}</a>
            </li>
        {% endfor %}
    {% endif %}
{% endblock tabs %}

{% block content %}
    <div>
        {% if user_profile %}
            {#        <div>{{ user_profile.goal_weight }}</div>#}
            {#        <div>{{ user_profile.last_name }}</div>#}
            <div>{{ user_profile.username }}</div>
        {% else %}
        <p>User is not found</p>
        {% endif %}
    </div>
{% endblock content %}

{% block profile %}
    <div class="card w-75 ps-5">
        <div class="border border-left border-right px-0">
            <div class="ps-3 pt-2 pb-2 border-bottom bg-dark">
                <h6 class="d-flex align-items-center mb-0 text-white">
                    News Feed  <i class="far fa-xs fa-star ms-auto text-primary"></i>
                </h6>
            </div>
            <div>
                <div class="card shadow-0">
                    <div class="card-body border-bottom pb-2">
                        <form class="row g-3" method="post">
                            {% csrf_token %}
                            <div class="d-flex">
                                <div class="d-flex align-items-center w-100 ps-3">
                                    {% if form.errors %}
                                        <p></p>
                                    {% else %}
                                        {{ form }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="d-flex align-items-center">
                                  <button type="submit" class="btn btn-primary btn-rounded">Share</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock profile %}

{% block notes %}
    <div class="card w-75 ps-5 mt-2">
        {% if comments %}
            {% for comment in comments %}
                <div class="d-flex flex-row p-3">
                        <img src="./static/img/no-user-image.jpeg" width="40" height="40" class="rounded-circle me-3">
                        <div class="w-100">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex flex-row align-items-center">
                                    <span class="mr-2 text-primary fw-bold">{{ comment.user.username }}</span>
                                </div>
                                <small>12h ago</small>
                            </div>
                            <p class="text-justify comment-text mb-0">{{ comment.body }}</p>
                            <div class="d-flex flex-row user-feed"> <span class="wish"><i class="fa fa-heartbeat mr-2"></i>24</span> <span class="ml-3"><i class="fa fa-comments-o mr-2"></i>Reply</span> </div>
                        </div>
                </div>
            {% endfor %}
        {% else %}
            <p></p>
        {% endif %}
    </div>

{% endblock notes %}

django-project/templates/index.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" value="Free online calorie counter and diet plan.
           Lose weight by tracking your caloric intake quickly and easily.
           Find nutrition facts for over 2,000,000 foods."
        >
        <title>{{ title }}</title>
        {% load static %} <!-- Instruct Django to load static files -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />
    </head>
    <body>
        <div class="container">
            <header>
                <ul class="nav nav-pills bg-primary ps-5" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link text-uppercase fs-6 fw-bold {% if navbar == 'home' %} active {% endif %}"
                                href="{% url 'main:home' %}">
                            My Home
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link text-uppercase fs-6 fw-bold {% if navbar == 'food' %} active {% endif %}"
                                href="{% url 'main:food' %}">
                            Food
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link text-uppercase fs-6 fw-bold {% if navbar == 'exercise' %} active {% endif %}"
                                href="{% url 'main:exercise' %}">
                            Exercise
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link text-uppercase fs-6 fw-bold {% if navbar == 'reports' %} active {% endif %}"
                                href="{% url 'main:reports' %}">
                            Reports
                        </a>
                    </li>
                </ul>
                <div class="tab-content bg-dark ps-5" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                        <ul class="nav nav-pills">
                            {% block tabs %}
                            {% endblock %}
                        </ul>
                    </div>
                </div>
            </header>
            {% block content %}
            {% endblock %}
            {% block profile %}
            {% endblock %}
            {% block notes %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
                integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
                crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
                integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
                crossorigin="anonymous">
        </script>
<!--            <script src="../../node_modules/bootstrap/js"></script>-->
<!--        <span class="message">{{ message }}</span>{{ content }}-->
<!--        <div><a href="about">About</a></div>-->
<!--        <div><a href="contact">Contact</a></div>-->
    </body>
</html>

django-project/templates/profile.html
{% extends 'index.html' %}

{% block content %}
    {% if user_profile %}
{#        <div>{{ user_profile.goal_weight }}</div>#}
{#        <div>{{ user_profile.last_name }}</div>#}
        <div>{{ user_profile.username }}</div>
    {% else %}
    <p>User is not found</p>
    {% endif %}
{% endblock content %}

{% block profile %}
<form class="row g-3" method="post">
    {% csrf_token %}
    <div class="d-flex">
        <div class="d-flex align-items-center w-100 ps-3">
            {% if form.errors %}
                <p></p>
            {% else %}
                {{ form }}
            {% endif %}
        </div>
    </div>
    <div class="d-flex justify-content-between">
        <div class="d-flex align-items-center">
          <button type="submit" class="btn btn-primary btn-rounded">Share</button>
        </div>
    </div>
</form>

{% endblock profile %}

{% block notes %}
{% if comments %}
    {% for comment in comments %}
        <div class="d-flex flex-row p-3">
                <img src="./static/img/no-user-image.jpeg" width="40" height="40" class="rounded-circle me-3">
                <div class="w-100">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex flex-row align-items-center">
                            <span class="mr-2 text-primary fw-bold">{{ comment.user.username }}</span>
                        </div>
                        <small>12h ago</small>
                    </div>
                    <p class="text-justify comment-text mb-0">{{ comment.body }}</p>
                    <div class="d-flex flex-row user-feed"> <span class="wish"><i class="fa fa-heartbeat mr-2"></i>24</span> <span class="ml-3"><i class="fa fa-comments-o mr-2"></i>Reply</span> </div>
                </div>
        </div>
    {% endfor %}
{% else %}
    <p></p>
{% endif %}

{% endblock notes %}

django-project/templates/reports.html
{% extends 'index.html' %}

{% block tabs %}
    {% if tabs %}
        {% for tab in tabs %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">{{ tab }}</a>
            </li>
        {% endfor %}
    {% endif %}
{% endblock tabs %}

{% block content %}
    <h1 class="container text-info" id="reports">Reports</h1>
{% endblock content %}